---
- name: Full sprite provisioning
  hosts: all
  become: true
  #vars_prompt:
  #  - name: tailscale_authkey
  #    prompt: "Tailscale authkey"
  #    private: true
  roles:
    - base
    - node
    - claude
    - secrets
    - tailscale
    - tmux
    - repo
    - tools
